
dataset: Dianping
seed: 42
epoches: 1000
batch_size: 1024
test_batch_size: 1024 # for test 2048
topks: '[20,10,5]'

emb_dim: 256
lr: 0.0001 # 0.0001
ui_n_layers: 2
ui_dropout: True
keep_prob_ui: 0.9
weight_decay: 0.0001   # 0.0001

schedule_type: linear
sigma_min: 0.0001
sigma_max: 1.0
item_freq_lambda: 0.5 # 0.5
gaussian_scale: 30  # gaussian_sigma = self.num_steps / world.args.gaussian_scale
num_step: 50

consistency_scale: 5 
consistency_mode: euler_solver    #freq_inference, euler_solver, p_reverse
consistency_loss_type: 'kl' # 'cross_entropy' 'kl'
beta_consistency: 0.7  
consistency_loss_lambda: 0.15  
ema_rate: 0.99

ssl_loss_lambda: 0.075 
tau: 0.6 # 0.6

sampling_scale: 30
sampling_type: recover  # agg
sampling_num_step: 50

aggregation_type: mean
timestep: layerwise




